### ISSUE TITLE
`CesiumSunSky` not accurate when far from the `CesiumGeoreference`

### ISSUE THREAD

**Issue by j9liu** [CesiumGS/cesium-unreal#1054] opened 2023-03-03 18:59 UTC
While adding the point cloud level to the Cesium for Unreal samples (https://github.com/CesiumGS/cesium-unreal-samples/pull/38), we found that the lighting is inaccurate when you fly far away from the `CesiumGeoreference`. For example, the time zone changes whenever you fly to a new point cloud in the point clouds level, so each point cloud should be brightly lit. Instead, the Mount St. Helens point cloud is very dark. Placing the georeference at Mount St. Helen fixes the lighting.

We thought this wouldn't happen in Unreal Engine 5.0+ because of double precision, but perhaps the calculations for sun position don't use double precision.

**Comment by kring** [comment] 2023-03-06 02:41
I just realized this is probably related to #527. It may even be the same exact issue!

**Comment by kring** [comment] 2023-07-17 02:58
Closing this as a duplicate of #527.

**Closed by kring** 2023-07-17 02:58 UTC
Labels: bug
