### ISSUE TITLE
Cesium Ion Assets panel displays deleted assets

### ISSUE THREAD

**Issue by wickerman123** [CesiumGS/cesium-unreal#546] opened 2021-07-12 11:34 UTC
If an asset is deleted or an upload fails to Cesium Ion, the assets panel in UE4 still shows the asset as available.

**Comment by argallegos** [comment] 2021-07-14 20:31
Hi @wickerman123 

We're looking into this issue, thanks for creating it. When you discovered it, did you already have the panel open before deleting the asset? Do they persist after closing the panel or restarting the editor?

**Comment by wickerman123** [comment] 2021-07-15 10:10
Hi, @argallegos 

Unfortunately I can't remember if I had the panel open or not but I'm fairly certain that not _all_ of my deleted assets are showing, only some.

**Comment by wickerman123** [comment] 2021-07-15 12:37
I just tested again and it seemed to work as expected, however there are still some deleted assets visible - one of which has the same name (but different ID of course) to another asset and the other does not. 

Could asset names be the issue here?

**Comment by wickerman123** [comment] 2021-07-15 13:48
I've just encountered another variant of this bug - the Assets panel is showing an asset that's upload was interrupted by a crash - said asset is not visible in My Assets however it does create another duplicate name situation as I simply just initiated the same upload once my system had recovered.

**Comment by argallegos** [comment] 2021-07-15 15:26
@wickerman123 I've done some testing on my side, and the biggest thing I noticed was that the panel doesn't really refresh unless you close and reopen it. On my end, tilesets (even with the same name) disappear once deleted, if I close and open the panel. 
To be clear, when you close and then re-open the ion assets panel, you still see previously deleted or improperly uploaded datasets? 
It sounds like only some datasets may be experiencing this issue. For the assets that have the same name, do they contain the same data? Or are they completely different tilesets that only share a name?

**Comment by argallegos** [comment] 2021-07-15 15:29
On the refreshing/ui side, this would be solved in part by adding a refresh button to the panel (https://github.com/CesiumGS/cesium-unreal/issues/332), since we don't necessarily want it to refresh on its own for performance. 

We'll still need to figure out what's up with assets that persist even on refreshing, though, so these issues should remain separate.

**Comment by kring** [comment] 2021-08-05 02:08
I'm going to close this because we can't reproduce the problem, other than the need for a refresh button, which is already covered by #332. Please reopen if you have additional information.

**Closed by kring** 2021-08-05 02:08 UTC
Labels: bug
