### ISSUE TITLE
Spawning two georeferenced actors in the same tick moves one of them to (0, 0, 0)

### ISSUE THREAD

**Issue by getinthedamnbox** [CesiumGS/cesium-unreal#498] opened 2021-06-21 14:22 UTC
I'm creating polylines using two `AActor` classes: `APoint` and `ASegment`. I also have two classes that derive from them: `ACesiumPoint` and `ACesiumSegment`. The only difference between the base and derived classes is that the derived ones have a `UCesiumGeoreferenceComponent`. The goal is to ensure that the polylines work even when the world origin is rebased.

When the user starts drawing a polyline, two `ACesiumPoint`s are spawned at the same location. The first one is supposed to stay there, whereas the second one starts getting its location updated by wherever the user is pointing. Everything works fine if I comment out the `UCesiumGeoreferenceComponent`:

```
//  in CesiumPoint.h
private:
  // UPROPERTY()
  // UCesiumGeoreferenceComponent* _georeferenceComponent;

// in CesiumPoint.cpp
ACesiumPoint::ACesiumPoint() {
  // _georeferenceComponent = CreateDefaultSubobject<UCesiumGeoreferenceComponent>(TEXT("Georeference"));
}
```

![point georeference bug_pc_good](https://user-images.githubusercontent.com/18287035/122776862-7c1bbb00-d279-11eb-82d4-462f067492eb.gif)

![point georeference bug_vr_good](https://user-images.githubusercontent.com/18287035/122777122-bbe2a280-d279-11eb-8310-c0523e4d8ce4.gif)

But if I uncomment those lines, adding the `UCesiumGeoreferenceComponent`, the first point gets moved to `(0, 0, 0)` when the second point is spawned. After that, placing points works normally again. It seems like the problem stems from two points getting spawned on the same tick.

![point georeference bug_pc_bad](https://user-images.githubusercontent.com/18287035/122777045-aa00ff80-d279-11eb-99b8-1a296fb4eb19.gif)

![point georeference bug_vr_bad](https://user-images.githubusercontent.com/18287035/122777143-bf762980-d279-11eb-86ca-17f31f1a8a55.gif)

Note that `KeepWorldOriginNearCamera` is off.

Another clue is that when I use my own tileset (not Cesium World Terrain) and try this in VR, not only does the second point get moved, but the camera gets moved as well.

Possibly related to #422. cc #330

**Comment by nithinp7** [comment] 2021-06-28 18:30
@getinthedamnbox I will look further into this soon, but do you know what the root component of the ACesiumPoint is? Is there a root component created and set in the constructor of the parent APoint class? I haven't tried it in a while, but iirc the georeference component (currently) doesn't work well as the root component. It should be added after the root component (can be a typical USceneComponent). That might not itself be relevant here, but I thought it might be worth mentioning.

**Comment by getinthedamnbox** [comment] 2021-06-28 20:24
@nithinp7 There's a `USceneComponent` as the root, yep. The `APoint` class looks like this:


### Point.h

```
#pragma once

#include <CoreMinimal.h>
#include <GameFramework/Actor.h>

#include "Point.generated.h"

/**
 * @brief Represents and displays a point in space.
 */
UCLASS()
class VRDASHBOARD_API APoint : public AActor {
  GENERATED_BODY()

public:
  APoint();

public:
  /**
   * @brief Moves the point to a location in space.
   *
   * @param location Where the point should be moved (in Unreal units).
   */
  void SetLocation(FVector location);

  /**
   * @brief Gets the point's location in space.
   *
   * @return location The point's location (in Unreal units).
   */
  FVector GetLocation();

protected:
  UPROPERTY()
  USceneComponent* Root;

private:
  /**
   * @brief Mesh used to represent the point in the level.
   */
  UPROPERTY(
      BlueprintReadOnly,
      VisibleAnywhere,
      meta = (AllowPrivateAccess = "true"))
  UStaticMeshComponent* _mesh;
};
```

### Point.cpp

```
#include "Point.h"

APoint::APoint() {
  PrimaryActorTick.bCanEverTick = false;

  Root = CreateDefaultSubobject<USceneComponent>("Root");
  _mesh = CreateDefaultSubobject<UStaticMeshComponent>("Mesh");

  RootComponent = Root;
  _mesh->SetupAttachment(Root);
}

void APoint::SetLocation(FVector location) { SetActorLocation(location); }

FVector APoint::GetLocation() { return GetActorLocation(); }
```

**Comment by javagl** [comment] 2021-07-03 19:14
I'm definitely lacking some context here, so apologies that I have to drop in a short "Wait...what?!" here:

> The only difference between the base and derived classes is that the derived ones have a UCesiumGeoreferenceComponent. The goal is to ensure that the polylines work even when the world origin is rebased.

There probably more behind that. But this sounds a bit like "We have to subclass all actors and attach a GeoRefComponent to them, so that they work in Cesium". This would be undesirable, to say the least. Is there a compelling reason to do this subclassing, or conversely: Could the same behavior _not_ be achieved by attaching that polyline to a parent actor, and making sure that (only!) the parent actor has a GeoRefComponent?

(Regardless of that: Spawning two actors with GeoRefComponents in the same tick **should** work, of course, and I'll try to reproduce the issue in view of some ongoing refactoring, but wanted to make sure that I understand the background a bit better...)

**Comment by getinthedamnbox** [comment] 2021-07-06 14:18
Thanks @javagl, you're not missing lots of context. I can explain why I did it this way, and we can discuss from there.

> Could the same behavior not be achieved by attaching that polyline to a parent actor, and making sure that (only!) the parent actor has a GeoRefComponent?

I thought about this, and here are the reasons why I went the other route:

1. I thought points and segments should work on their own out of the box, without needing any special parenting setup.
2. Points and segments will likely need other Cesium-specific functionality (e.g., getting/setting ECEF location, getting altitude/height), so that would go in `ACesiumPoint` and `ACesiumSegment`.

So, overall, I was aiming for ease of use. If you want a point in the level, you just spawn `ACesiumPoint`, and it works. You can get/set georeferenced info straight through it.

That said, if it's worthwhile to limit how many actors with `UCesiumGeoreferenceComponent`s are in the level, it's certainly possible to take the other approach and ensure that whenever points and segments are spawned, they're parented to a georeferenced actor. We could have manager classes for points and segments and/or have a utility function for spawning actors of any type, which would automatically parent them to a georeferenced actor. And any Cesium-specific functionality could go through the manager classes or utility functions.

cc @xuelongmu, who is working on this going forward.

**Comment by kring** [comment] 2022-05-03 12:46
Closing this one too because we don't know how to reproduce it and it's hopefully not happening anymore. Please reopen if you see it again.

**Closed by kring** 2022-05-03 12:46 UTC
Labels: bug
