### ISSUE TITLE
warning C4819: the file contains characters that cannot be represented in the current code page (936)

### ISSUE THREAD

**Issue by 137734949** [CesiumGS/cesium-unreal#702] opened 2021-12-07 04:51 UTC
cesium-unreal\extern\cesium-native\extern\s2geometry\src\s2/base/port.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失

**Comment by wxp1989** [comment] 2021-12-07 06:09
S2CellID.cpp中#pragma warning(disable : 4100 4127 4309 4996)修改为#pragma warning(disable : 4100 4127 4309 4996 4819)

**Comment by 137734949** [comment] 2021-12-07 06:21
多谢

**Comment by kring** [comment] 2022-05-09 11:01
The problem is that the port.h file included with s2geometry includes non-ASCII characters, specifically the quotes in `“ARMv7 or higher”`. And that plus a codepage that doesn't support those characters and the fact that Visual Studio doesn't treat source files as UTF-8 unless they have a byte order mark, leads to the error. You can fix it by removing the quotes or suppressing the warning. Or perhaps changing your codepage.

It looks like s2geometry v0.10.0 has already removed this (or at least moved it elsewhere, I'm not sure), so there's not really much more to do here. So I'm closing this.

**Closed by kring** 2022-05-09 11:01 UTC
