### ISSUE TITLE
How to optimize the loading speed of 3dtile

### ISSUE THREAD

**Issue by hahaxiaowai** [CesiumGS/cesium-unreal#1048] opened 2023-02-26 09:41 UTC
I want to load a lot of 3Dtile.
When I move the camera to a new place,3dtile looks like loading the tiles in the distance first.Then load nearby.
This seems to be caused by loading the parent -level first and then loading sub -level.
How to skip  parent level loading?

**Comment by kring** [comment] 2023-02-26 10:21
With the default settings, Cesium for Unreal prioritizes tiles that are nearby and near the center of the camera. And it also skips levels of detail, but not to the point of making the user wait and see nothing for too long. You can tweak this balance by changing the `Loading Descendant Limit` property on the tileset to a larger number.

I'm closing this because it's not a bug report or a feature request. Please post questions like this to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10) instead.

**Closed by kring** 2023-02-26 10:21 UTC
