### ISSUE TITLE
Provide a pawn similar to Google Erath

### ISSUE THREAD

**Issue by lidongzhuo** [CesiumGS/cesium-unreal#720] opened 2022-01-12 02:22 UTC
Can you provide a pawn similar to Google Erath, which can ensure that the map always follows the mouse when panning, and can rotate and pitch around the center of the screen, as well as zoom.

**Comment by kring** [comment] 2022-01-14 07:59
This is a duplicate of #519. It's definitely something we'd like to do, but can't commit to a time frame for it at the moment.

**Closed by kring** 2022-01-14 07:59 UTC
