### ISSUE TITLE
When moving the scene, the camera is at an Angle, tileset missing in view center。

### ISSUE THREAD

**Issue by luojianqi** [CesiumGS/cesium-unreal#1457] opened 2024-06-18 08:41 UTC
Hi, I have a question right now. I used cesium for unreal2.6 in Unreal Engine 5.3 to load the tilting model, and when moving the scene, the camera's at an Angle，tileset missing in view center。 It is very regular, but I can't find the problem, I hope you can help me, thank you very much!The picture is as follows。

**Comment by luojianqi** [comment] 2024-06-18 08:49
![Uploading 1.png…]()
![2](https://github.com/CesiumGS/cesium-unreal/assets/65322033/c2d1777b-98f6-4926-92c2-2a17f326cec1)
![Uploading 3.png…]()

**Comment by luojianqi** [comment] 2024-06-18 08:51
![1](https://github.com/CesiumGS/cesium-unreal/assets/65322033/c57aae47-bff2-4575-99af-844100cbd1ba)
![2](https://github.com/CesiumGS/cesium-unreal/assets/65322033/729cb960-cdee-4792-96aa-d2caff62ac9f)
![3](https://github.com/CesiumGS/cesium-unreal/assets/65322033/24886bac-cc15-445e-9346-a2f7fd5815e6)

**Comment by kring** [comment] 2024-06-19 11:23
It's hard to say for sure what's going on. When tiles are missing like that, my first guess is usually that there is something wrong with the bounding volumes in the tileset itself. So, what tileset is this? How was it created? Do you see the same problem with other tilesets as well (especially the Cesium-provided ones)?

As for the tilted camera, it's normal for that to happen in the Editor as you move away from the origin, because the Earth is not flat, and Unreal's Editor camera always maintains +Z is up. You can select the CesiumGeoreference and click "Place Georeference Here" to move the origin to the current location of the Editor camera, and that should right things. If you're seeing it in-game, it may be because there's no CesiumGlobeAnchor on your Pawn. Using the DynamicCamera provided by the plugin is a quick way to avoid this in-game.

I'm going to close this issue because there's nothing actionable for us here. Please follow up on our [community forum](https://community.cesium.com/c/cesium-for-unreal/10) instead, where the Cesium for Unreal developers and other members of the community can answer your questions. We only use GitHub for confirmed bugs and clear feature requests.

**Closed by kring** 2024-06-19 11:23 UTC
