### ISSUE TITLE
How to use the mouse to rotate, pan, and zoom the scene like cesiumjs？Have a BluePrint Node?

### ISSUE THREAD

**Issue by lky5230** [CesiumGS/cesium-unreal#1567] opened 2024-12-07 02:47 UTC
How to use the mouse to rotate, pan, and zoom the scene like cesiumjs？Have a BluePrint Node?

**Comment by kring** [comment] 2024-12-12 05:27
There's currently no built-in support for this. Closing this issue because it's a duplicate of #519.

**Closed by kring** 2024-12-12 05:27 UTC
