### ISSUE TITLE
White tiles appearing briefly in sequencer renders

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unreal#300] opened 2021-04-02 18:22 UTC
Recently when rendering sequencer shots of photogrammetry datasets, I'll get strange flashing white tiles appearing in the final render. It looks like the tile is vanishing briefly or something similar, but the white tiles aren't showing anything behind them, so possibly it's a material issue.
I'll try to grab an example of this happening with a public dataset.

**Comment by kring** [comment] 2021-04-28 01:09
Any update on this @argallegos? It sounds like it could be related to CesiumGS/cesium-native#186.

**Comment by kring** [comment] 2021-06-29 05:03
I don't think anyone is actually working on this, so I've updated the status to reflect that.

**Comment by kring** [comment] 2021-06-29 06:28
Actually I think I'll close this since it's not really actionable. I just tried a sequencer render and didn't see any flashing. But if you're still seeing it @argallegos, please re-open with some steps to reproduce.

**Closed by kring** 2021-06-29 06:28 UTC
Labels: bug
