### ISSUE TITLE
Cesium3DTileset.cpp:944  Unhandled Exception: EXCEPTION_ACCESS_VIOLATION writing address 0x0000000000000128

### ISSUE THREAD

**Issue by zmuye** [CesiumGS/cesium-unreal#489] opened 2021-06-10 02:45 UTC
I create a ue c++ project。Using UE(4.26) , cesium-unreal（CesiumForUnreal-v1.3.1） and Pixel Streaming（bete 0.2） plugins，and making different level for iamge and road data sourceI ，I  change data source by clicking button on my webpage 。
When I clicked “Image” button, it work well。then clicked “Road”，it work well。But，when I click “Image” again，it crashed。I have no idea now 。please help：:stuck_out_tongue_winking_eye: 。
![demo-image](https://user-images.githubusercontent.com/17806212/121455282-c4fc8580-c9d6-11eb-8284-2c8743a1a231.jpg)

![demo-road](https://user-images.githubusercontent.com/17806212/121456739-1b6ac380-c9d9-11eb-9b59-263e6dd0ef0d.png)

![demo-image-cr](https://user-images.githubusercontent.com/17806212/121457116-ba8fbb00-c9d9-11eb-9b42-f9ae67b436b0.png)

my level blueprint：
![print1](https://user-images.githubusercontent.com/17806212/121459372-b36aac00-c9dd-11eb-8491-2f444392434a.png)
![print2](https://user-images.githubusercontent.com/17806212/121459635-32f87b00-c9de-11eb-805a-efeee52d4040.png)
![print3](https://user-images.githubusercontent.com/17806212/121459378-b49bd900-c9dd-11eb-9821-ed9487560200.png)
![print4](https://user-images.githubusercontent.com/17806212/121459379-b5346f80-c9dd-11eb-86eb-19dea81b3574.png)
![print5](https://user-images.githubusercontent.com/17806212/121459380-b5346f80-c9dd-11eb-9dce-65bbe57de041.png)
![print6](https://user-images.githubusercontent.com/17806212/121459381-b5cd0600-c9dd-11eb-85c8-d6a25c270530.png)
![print7](https://user-images.githubusercontent.com/17806212/121459648-3a1f8900-c9de-11eb-9e1a-ba6cacc73a9b.png)

THE  ERROR LOG as this: 
###########
LoginId:1700c9174480de95c2f99b846bd241f5
EpicAccountId:bd9d5e0d1b4e4b6f91d30a90b0beec83

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION writing address 0x0000000000000128

UE4Editor_CesiumRuntime_Win64_DebugGame!ACesium3DTileset::Tick() [E:\zhangzhi\uedev\CesiumPixelStreamingDemo\cpsdemocppzz\Plugins\CesiumForUnreal\Source\CesiumRuntime\Private\Cesium3DTileset.cpp:944]
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Core

UE4Editor_Core
UE4Editor_Core
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Win64_DebugGame
UE4Editor_Win64_DebugGame
UE4Editor_Win64_DebugGame
UE4Editor_Win64_DebugGame
UE4Editor_Win64_DebugGame
kernel32
ntdll
###########
LOG FILE ：
##########
[cpsdemocpp_2.log](https://github.com/CesiumGS/cesium-unreal/files/6628029/cpsdemocpp_2.log)

#######

**Comment by kring** [comment] 2021-06-29 08:48
@zmuye it's hard to say what is going wrong here. Are you able to share a minimal project with us to reproduce this issue?

**Comment by kring** [comment] 2021-08-05 01:23
Closing this due to lack of information. Please reopen if you have anything to add.

**Closed by kring** 2021-08-05 01:23 UTC
Labels: bug
