### ISSUE TITLE
Developer setup CMake GUI/Command line instructions are not working

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unreal#719] opened 2022-01-10 15:28 UTC
[User on the forums](https://community.cesium.com/t/development-setup/16792) and @nithinp7 confirmed that there is an issue preventing users from building Cesium Native when trying to complete the developer setup via the CMake GUI (and probably CMake command line) instructions.

It looks like the cmakepredefinedtargets folder is not being created. 

Developer setup should be tested and revised if needed.

**Comment by markemerge** [comment] 2022-04-30 19:09
I have been trying to get the Cesium plugin working in Unreal 5 on Mac without much luck. The normal plugin installation method through the launcher did not work for me. I investigated further and it seems that a user has to make for OSX but I wasn't successful. Any guidance on how to create a Cesium Unreal project on my mac is appreciated.

I have been unable to build the Unreal Plugin on Mac OS X using the following instructions:

> https://github.com/CesiumGS/cesium-unreal/blob/ue5-main/Documentation/developer-setup-osx.md

When running 
```bash
cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
```

Seems the first error is related to needing a dependency:

```cmake
-- Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR) (found version "")
```

And the next two errors seem to be related to a makelist:

```
CMake Error at cesium-native/extern/KTX-Software/CMakeLists.txt:685 (add_subdirectory):
  add_subdirectory given source "tools" which is not an existing directory.

CMake Error at cesium-native/extern/KTX-Software/CMakeLists.txt:689 (add_subdirectory):
  add_subdirectory given source "tests" which is not an existing directory.
```

Full output below:
```
➜  extern git:(ue5-main) cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
-- Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR) (found version "")
-- Vulkan SDK not found -> skipping mkvk target (this is harmless; only needed when re-generating of vulkan headers and dfdutils is required)
--   AVX2 backend    - OFF
--   SSE4.1 backend  - OFF
--   SSE2 backend    - OFF
--   NEON backend    -  ON
--   NONE backend    - OFF
--   NATIVE backend  - OFF
--   Universal bin   - OFF
--   Decompressor    - OFF
--   Diagnostics     - OFF
--   Unit tests      - OFF
CMake Error at cesium-native/extern/KTX-Software/CMakeLists.txt:685 (add_subdirectory):
  add_subdirectory given source "tools" which is not an existing directory.


CMake Error at cesium-native/extern/KTX-Software/CMakeLists.txt:689 (add_subdirectory):
  add_subdirectory given source "tests" which is not an existing directory.


-- ===========================================================================
-- 
-- Configuration
--   Prefix ............... /Users/sparkyspider/dev/cesium-unreal-samples/Plugins/cesium-unreal/extern/../Source/ThirdParty
--   Shared libraries ..... OFF
--   Code for char * ...... ON
--   Code for wchar_t * ... ON
--   Tools ................ OFF
--   Test suite ........... OFF
--   Documentation ........ OFF
-- 
-- Continue with
--   make
--   make test
--   sudo make install
-- 
-- ===========================================================================
-- Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) 
CMake Deprecation Warning at cesium-native/extern/tinyxml2/CMakeLists.txt:8 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at cesium-native/extern/tinyxml2/CMakeLists.txt:9 (cmake_policy):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at cesium-native/extern/tinyxml2/CMakeLists.txt:11 (cmake_policy):
  The OLD behavior for policy CMP0063 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


CMake Warning (dev) at cesium-native/extern/tinyxml2/CMakeLists.txt:14 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Build spdlog: 1.8.1
-- Build type: Release
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Configuring incomplete, errors occurred!
See also "/Users/sparkyspider/dev/cesium-unreal-samples/Plugins/cesium-unreal/extern/build/CMakeFiles/CMakeOutput.log".
See also "/Users/sparkyspider/dev/cesium-unreal-samples/Plugins/cesium-unreal/extern/build/CMakeFiles/CMakeError.log".
➜  extern git:(ue5-main) cmake --build build --target install          
make: Makefile: No such file or directory
make: *** No rule to make target `Makefile'.  Stop.
➜  extern git:(ue5-main) 
```

**Comment by sparkyspider** [comment] 2022-04-30 19:11
I have been trying to get the Cesium plugin working in Unreal 5 on Mac without much luck. The normal plugin installation method through the launcher did not work for me. I investigated further and it seems that a user has to make for OSX but I wasn't successful. Any guidance on how to create a Cesium Unreal project on my mac is appreciated.

I have been unable to build the Unreal Plugin on Mac OS X using the following instructions:

> https://github.com/CesiumGS/cesium-unreal/blob/ue5-main/Documentation/developer-setup-osx.md

When running 
```bash
cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
```

Seems the first error is related to needing a dependency:

```cmake
-- Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR) (found version "")
```

And the next two errors seem to be related to a makelist:

```
CMake Error at cesium-native/extern/KTX-Software/CMakeLists.txt:685 (add_subdirectory):
  add_subdirectory given source "tools" which is not an existing directory.

CMake Error at cesium-native/extern/KTX-Software/CMakeLists.txt:689 (add_subdirectory):
  add_subdirectory given source "tests" which is not an existing directory.
```

Full output below:
```
➜  extern git:(ue5-main) cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
-- Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR) (found version "")
-- Vulkan SDK not found -> skipping mkvk target (this is harmless; only needed when re-generating of vulkan headers and dfdutils is required)
--   AVX2 backend    - OFF
--   SSE4.1 backend  - OFF
--   SSE2 backend    - OFF
--   NEON backend    -  ON
--   NONE backend    - OFF
--   NATIVE backend  - OFF
--   Universal bin   - OFF
--   Decompressor    - OFF
--   Diagnostics     - OFF
--   Unit tests      - OFF
CMake Error at cesium-native/extern/KTX-Software/CMakeLists.txt:685 (add_subdirectory):
  add_subdirectory given source "tools" which is not an existing directory.


CMake Error at cesium-native/extern/KTX-Software/CMakeLists.txt:689 (add_subdirectory):
  add_subdirectory given source "tests" which is not an existing directory.


-- ===========================================================================
-- 
-- Configuration
--   Prefix ............... /Users/sparkyspider/dev/cesium-unreal-samples/Plugins/cesium-unreal/extern/../Source/ThirdParty
--   Shared libraries ..... OFF
--   Code for char * ...... ON
--   Code for wchar_t * ... ON
--   Tools ................ OFF
--   Test suite ........... OFF
--   Documentation ........ OFF
-- 
-- Continue with
--   make
--   make test
--   sudo make install
-- 
-- ===========================================================================
-- Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) 
CMake Deprecation Warning at cesium-native/extern/tinyxml2/CMakeLists.txt:8 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at cesium-native/extern/tinyxml2/CMakeLists.txt:9 (cmake_policy):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at cesium-native/extern/tinyxml2/CMakeLists.txt:11 (cmake_policy):
  The OLD behavior for policy CMP0063 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


CMake Warning (dev) at cesium-native/extern/tinyxml2/CMakeLists.txt:14 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Build spdlog: 1.8.1
-- Build type: Release
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Configuring incomplete, errors occurred!
See also "/Users/sparkyspider/dev/cesium-unreal-samples/Plugins/cesium-unreal/extern/build/CMakeFiles/CMakeOutput.log".
See also "/Users/sparkyspider/dev/cesium-unreal-samples/Plugins/cesium-unreal/extern/build/CMakeFiles/CMakeError.log".
➜  extern git:(ue5-main) cmake --build build --target install          
make: Makefile: No such file or directory
make: *** No rule to make target `Makefile'.  Stop.
➜  extern git:(ue5-main) 
```

**Comment by baothientran** [comment] 2022-05-04 16:55
@sparkyspider I think the Vulkan dependency isn't required by the CMake, so it will skip it in this case.  I'm unable to reproduce the other two errors:
```
CMake Error at cesium-native/extern/KTX-Software/CMakeLists.txt:685 (add_subdirectory):
  add_subdirectory given source "tools" which is not an existing directory.


CMake Error at cesium-native/extern/KTX-Software/CMakeLists.txt:689 (add_subdirectory):
  add_subdirectory given source "tests" which is not an existing directory.
```

If possible, can you please check if there are two directories `tools` and `tests` in the `cesium-unreal/extern/cesium-native/extern/KTX-Software`?

Another thing to try is that after invoking `cmake -B build -S .` in the `cesium-unreal/extern`, there will be a `build` directory with `CMakeCache.txt` in there. Can you search for `KTX_FEATURE_TOOLS:BOOL=ON` in that file and modify it to `KTX_FEATURE_TOOLS:BOOL=OFF`, then invoke the cmake commad again? You may want to try the same with `KTX_FEATURE_TESTS:BOOL=OFF`

**Comment by baothientran** [comment] 2022-05-04 18:28
If those two directories doesn't exist, there is a good chance that the `cesium-native` may be corrupted somehow during the git cloning steps. If possible can you please remove the `cesium-unreal` directory and re-clone it again, and re-check if those two directories exist in the KTX-Software directory? I can see those directories on my Mac, but not sure why they don't exist on your side

For convenience, you can choose one of the commands below:
```
git clone --recursive https://github.com/CesiumGS/cesium-unreal.git
```

```
git clone https://github.com/CesiumGS/cesium-unreal.git
git submodule update --init --recursive
```

**Comment by markemerge** [comment] 2022-05-07 19:20
Hi @baothientran 

It looks like you're right. Seems some of my dependencies are failing. I tried this a few times and it seems to stop at the same place:
```
Cloning into 'cesium-unreal'...
remote: Enumerating objects: 18631, done.
remote: Counting objects: 100% (1896/1896), done.
remote: Compressing objects: 100% (769/769), done.
remote: Total 18631 (delta 1097), reused 1863 (delta 1077), pack-reused 16735
Receiving objects: 100% (18631/18631), 48.37 MiB | 2.74 MiB/s, done.
Resolving deltas: 100% (11013/11013), done.
Submodule 'extern/MikkTSpace' (https://github.com/mmikk/MikkTSpace.git) registered for path 'extern/MikkTSpace'
Submodule 'extern/cesium-native' (https://github.com/CesiumGS/cesium-native.git) registered for path 'extern/cesium-native'
...
...
Cloning into '/Users/sparkyspider/dev/cesium-unreal-samples/Plugins/cesium-unreal/extern/cesium-native/extern/rapidjson/thirdparty/gtest'...
remote: Enumerating objects: 24344, done.        
remote: Counting objects: 100% (9/9), done.        
remote: Compressing objects: 100% (7/7), done.        
remote: Total 24344 (delta 1), reused 5 (delta 1), pack-reused 24335        
Receiving objects: 100% (24344/24344), 10.18 MiB | 2.62 MiB/s, done.
Resolving deltas: 100% (18013/18013), done.
Submodule path 'extern/cesium-native/extern/rapidjson/thirdparty/gtest': checked out 'ba96d0b1161f540656efdaed035b3c062b60e006'
Submodule path 'extern/cesium-native/extern/s2geometry': checked out '4ad31e9b9d4b25f0ddffa2061ac5a7d14edf7195'
Submodule path 'extern/cesium-native/extern/spdlog': checked out 'cbe9448650176797739dbab13961ef4c07f4290f'
Submodule path 'extern/cesium-native/extern/stb': checked out 'b42009b3b9d4ca35bc703f5310eedc74f584be58'
Submodule path 'extern/cesium-native/extern/tinyxml2': checked out '1aeb57d26bc303d5cfa1a9ff2a331df7ba278656'
Submodule path 'extern/cesium-native/extern/uriparser': checked out 'e8a338e0c65fd875a46067d711750e4c13e044e7'
Unable to checkout '94764c270d43d90e4e4cedee6248753296f874b3' in submodule path 'extern/cesium-native/extern/KTX-Software'
Failed to recurse into submodule path 'extern/cesium-native'
```

Note the last line. Ideas?

**Comment by kring** [comment] 2022-05-09 12:26
I just submitted a PR to solve the _original_ problem described by this issue by updating the instructions:
https://github.com/CesiumGS/cesium-unreal/pull/843
That problem was on Windows and Visual Studio.

The posts since have been on macOS, and unfortunately I don't have a solution there. I guess I'd suggest checking for things like lack of disk space, an old git version, network configuration (e.g. a proxy) that prevents access to https git repos. In case it helps, the specific commit that the error message says it can't check out this one:
https://github.com/CesiumGS/KTX-Software/commit/94764c270d43d90e4e4cedee6248753296f874b3

**Comment by kring** [comment] 2022-05-09 12:27
I'm going to close this because I don't think there's any action on our side. But if you're still having trouble, please post to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10).

**Closed by kring** 2022-05-09 12:27 UTC

**Comment by markemerge** [comment] 2022-05-15 19:10
Hi @kring I found the issue. I needed git-lfs installed on my local machine to be able to clone the KTX-Software sub-dependency. It may be worth adding it to the dependency list here:

https://github.com/CesiumGS/cesium-unreal/blob/ue5-main/Documentation/developer-setup-osx.md

**Comment by kring** [comment] 2022-05-16 06:07
Good detective work @markemerge, thanks for letting us know! I wrote an issue to update the docs here:
https://github.com/CesiumGS/cesium-unreal/issues/852
