### ISSUE TITLE
Compile Error of CesiumMetadataPrimitive.h(104) 

### ISSUE THREAD

**Issue by DeLaMercedRichard** [CesiumGS/cesium-unreal#918] opened 2022-07-21 17:02 UTC
CompilerResultsLog: Error: D:/Github/convis/Plugins/CesiumForUnreal/Source/CesiumRuntime/Public/CesiumMetadataPrimitive.h(104)  : Error: Unrecognized type 'FCesiumFeatureIdAttribute' - type must be a UCLASS, USTRUCT or UENUM 

`{
	"FileVersion": 3,
	"Version": 28,
	"VersionName": "1.14.0",
	"FriendlyName": "Cesium for Unreal",
	"Description": "Unlock the 3D geospatial ecosystem in Unreal Engine with real-world 3D content and a high accuracy full-scale WGS84 globe.",
	"Category": "Geospatial",
	"CreatedBy": "Cesium GS, Inc.",
	"CreatedByURL": "https://cesium.com",
	"DocsURL": "https://cesium.com/learn/unreal/",
	"MarketplaceURL": "com.epicgames.launcher://ue/marketplace/content/87b0d05800a545d49bf858ef3458c4f7",
	"SupportURL": "https://community.cesium.com",
	"EngineVersion": "4.27.0",
	"CanContainContent": true,
	"Installed": true,
	"SupportedTargetPlatforms": [
		"Win64",
		"Mac",
		"Linux",
		"Android",
		"IOS"
	],
	"Modules": [
		{
			"Name": "CesiumRuntime",
			"Type": "Runtime",
			"LoadingPhase": "Default",
			"WhitelistPlatforms": [
				"Win64",
				"Mac",
				"Linux",
				"Android",
				"IOS"
			]
		},
		{
			"Name": "CesiumEditor",
			"Type": "Editor",
			"LoadingPhase": "PostEngineInit",
			"WhitelistPlatforms": [
				"Win64",
				"Mac",
				"Linux",
				"Android",
				"IOS"
			]
		}
	],
	"Plugins": [
		{
			"Name": "WebBrowserWidget",
			"Enabled": true
		},
		{
			"Name": "SunPosition",
			"Enabled": true
		},
		{
			"Name": "Water",
			"Enabled": true
		}
	]
}`

**Comment by kring** [comment] 2022-07-22 00:16
Hi @DeLaMercedRichard, we're going to need more information to help diagnose this. Which branch/commit are you trying to build? Which platform? How are you building it? Our code is automatically built on every commit by a continuous integration system, so we're quite confident it compiles, but there could still be machine-specific configuration problems. I'm going to close this; please followup on the [community forum](https://community.cesium.com/c/cesium-for-unreal/10) because we generally only use GitHub for confirmed bugs and feature requests.

**Closed by kring** 2022-07-22 00:16 UTC
