### ISSUE TITLE
The use of cesium and landscape together causes the problem of landscape position error

### ISSUE THREAD

**Issue by w13315071023** [CesiumGS/cesium-unreal#610] opened 2021-08-26 09:53 UTC
UE4.26.2
cesium for unreal 1.5.1
在场景中创建了一个landscape，和一套CesiumWorldTerrain。通过CesiumGeoreference设置坐标经纬度，与landscape坐标重合，场景中使用得是自定义得APawn作为一个角色，然后再UMG中创建一个按钮 来根据实际位置设置角色在场景中得位置，发现设置pawn的x:123671.258，y:165101.000，z为pawn的自身以后，每设置一次，landscape的位置就会偏移一次（代码和蓝图中没有任何地方设置landscape的位置），删除cesium套件后正常。
![XP7KZTP{V69_J)(X903EZ)D](https://user-images.githubusercontent.com/16461641/130942057-49e28aea-4dec-4b1d-aa82-05feb089abcf.jpg)
![%C)AJ(LEZX~O~TIMOK8D30Z](https://user-images.githubusercontent.com/16461641/130942101-08607f78-e59a-46b0-b8c0-22cd85afbce9.png)
![7IZ3P3PISP7G SGP4`(Y~PY](https://user-images.githubusercontent.com/16461641/130942106-938d6ee8-ba70-44d8-bd21-73eb7a1786f7.png)
![LI965E)UO$Z@54`Z$715DZG](https://user-images.githubusercontent.com/16461641/130942108-419c7e54-79c0-4276-8fb6-12ca43a8f991.png)

**Comment by kring** [comment] 2022-05-09 07:17
Translation:

>UE4.26.2
cesium for unreal 1.5.1
Created a landscape in the scene, and a set of CesiumWorldTerrain. Set the latitude and longitude of the coordinates through CesiumGeoreference, which coincides with the coordinates of the landscape. In the scene, a custom APawn is used as a character, and then a button is created in UMG to set the position of the character in the scene according to the actual position. It is found that the x:123671.258 of the pawn is set. , y: 165101.000, after z is the pawn itself, the position of the landscape will be shifted once every time it is set (there is no place to set the position of the landscape in the code and blueprint), it is normal after deleting the cesium kit.

**Comment by kring** [comment] 2022-05-09 07:19
This is most likely caused by the "Keep World Origin Near Camera" option on CesiumGeoreference combined with a bug in landscapes where they don't respond to origin rebasing. Unticking that should help. In UE5, we no longer need to do origin rebasing because the engine supports double coordinates. Closing this.

**Closed by kring** 2022-05-09 07:19 UTC
