### ISSUE TITLE
Unreal5.2 BuildFail

### ISSUE THREAD

**Issue by ClaspU** [CesiumGS/cesium-unreal#1522] opened 2024-09-14 10:58 UTC
My project used the Cesium plugin, but failed to package it. Prior to this, it was possible to package it successfully. This blueprint project reported an error due to a failed connection to the dynamic library. The log is as follows：
[2024.09.14-07.39.39:948][761]UATHelper: 打包 (Windows):   ���ڴ����� G:\Workproject\1_Yuanshan\yuanshan-model\Binaries\Win64\YuanShan.lib �Ͷ��� G:\Workproject\1_Yuanshan\yuanshan-model\Binaries\Win64\YuanShan.exp
[2024.09.14-07.39.39:969][762]UATHelper: 打包 (Windows): Cesium3DTilesReader.lib(SubtreeFileReader.obj) : error LNK2001: �޷��������ⲿ���� __std_find_trivial_8
[2024.09.14-07.39.39:969][762]UATHelper: 打包 (Windows): CesiumRasterOverlays.lib(WebMapServiceRasterOverlay.obj) : error LNK2001: �޷��������ⲿ���� __std_find_trivial_8
[2024.09.14-07.39.39:969][762]UATHelper: 打包 (Windows): CesiumRasterOverlays.lib(RasterOverlayTileProvider.obj) : error LNK2001: �޷��������ⲿ���� __std_find_trivial_8
[2024.09.14-07.39.39:969][762]UATHelper: 打包 (Windows): CesiumRasterOverlays.lib(QuadtreeRasterOverlayTileProvider.obj) : error LNK2001: �޷��������ⲿ���� __std_find_trivial_8
[2024.09.14-07.39.39:969][762]UATHelper: 打包 (Windows): Cesium3DTilesContent.lib(SubtreeAvailability.obj) : error LNK2001: �޷��������ⲿ���� __std_find_trivial_8
[2024.09.14-07.39.39:969][762]UATHelper: 打包 (Windows): CesiumRasterOverlays.lib(BingMapsRasterOverlay.obj) : error LNK2001: �޷��������ⲿ���� __std_find_trivial_8
[2024.09.14-07.39.39:969][762]UATHelper: 打包 (Windows): CesiumRasterOverlays.lib(IonRasterOverlay.obj) : error LNK2001: �޷��������ⲿ���� __std_find_trivial_8
[2024.09.14-07.39.39:969][762]UATHelper: 打包 (Windows): CesiumRasterOverlays.lib(RasterizedPolygonsOverlay.obj) : error LNK2001: �޷��������ⲿ���� __std_find_trivial_8
[2024.09.14-07.39.39:969][762]UATHelper: 打包 (Windows): CesiumRasterOverlays.lib(TileMapServiceRasterOverlay.obj) : error LNK2001: �޷��������ⲿ���� __std_find_trivial_8
[2024.09.14-07.39.39:969][762]UATHelper: 打包 (Windows): Cesium3DTilesSelection.lib(ImplicitQuadtreeLoader.obj) : error LNK2001: �޷��������ⲿ���� __std_find_trivial_8
[2024.09.14-07.39.39:969][762]UATHelper: 打包 (Windows): CesiumAsync.lib(CachingAssetAccessor.obj) : error LNK2001: �޷��������ⲿ���� __std_find_trivial_8
[2024.09.14-07.39.39:969][762]UATHelper: 打包 (Windows): CesiumAsync.lib(GunzipAssetAccessor.obj) : error LNK2001: �޷��������ⲿ���� __std_find_trivial_8
[2024.09.14-07.39.39:969][762]UATHelper: 打包 (Windows): CesiumGltfReader.lib(GltfReader.obj) : error LNK2001: �޷��������ⲿ���� __std_find_trivial_8
[2024.09.14-07.39.39:969][762]UATHelper: 打包 (Windows): Cesium3DTilesSelection.lib(CesiumIonTilesetLoader.obj) : error LNK2001: �޷��������ⲿ���� __std_find_trivial_8
[2024.09.14-07.39.39:980][762]UATHelper: 打包 (Windows): Cesium3DTilesSelection.lib(LayerJsonTerrainLoader.obj) : error LNK2001: �޷��������ⲿ���� __std_find_trivial_8
[2024.09.14-07.39.39:980][762]UATHelper: 打包 (Windows): Cesium3DTilesSelection.lib(TilesetJsonLoader.obj) : error LNK2001: �޷��������ⲿ���� __std_find_trivial_8
[2024.09.14-07.39.39:980][762]UATHelper: 打包 (Windows): Cesium3DTilesSelection.lib(ImplicitOctreeLoader.obj) : error LNK2001: �޷��������ⲿ���� __std_find_trivial_8
[2024.09.14-07.39.39:980][762]UATHelper: 打包 (Windows): Cesium3DTilesSelection.lib(TilesetMetadata.obj) : error LNK2001: �޷��������ⲿ���� __std_find_trivial_8
[2024.09.14-07.39.39:980][762]UATHelper: 打包 (Windows): Cesium3DTilesSelection.lib(RasterOverlayCollection.obj) : error LNK2001: �޷��������ⲿ���� __std_find_trivial_8
[2024.09.14-07.39.39:980][762]UATHelper: 打包 (Windows): Cesium3DTilesSelection.lib(TilesetContentManager.obj) : error LNK2001: �޷��������ⲿ���� __std_find_trivial_8
[2024.09.14-07.39.39:980][762]UATHelper: 打包 (Windows): Cesium3DTilesSelection.lib(RasterOverlayUpsampler.obj) : error LNK2001: �޷��������ⲿ���� __std_find_trivial_8
[2024.09.14-07.39.39:980][762]UATHelper: 打包 (Windows): Module.CesiumRuntime.8_of_11.cpp.obj : error LNK2001: �޷��������ⲿ���� __std_find_trivial_8
[2024.09.14-07.39.39:980][762]UATHelper: 打包 (Windows): Module.CesiumRuntime.10_of_11.cpp.obj : error LNK2001: �޷��������ⲿ���� __std_find_trivial_8
[2024.09.14-07.39.39:980][762]UATHelper: 打包 (Windows): Module.CesiumRuntime.11_of_11.cpp.obj : error LNK2001: �޷��������ⲿ���� __std_find_trivial_8
[2024.09.14-07.39.39:980][762]UATHelper: 打包 (Windows): Cesium3DTilesSelection.lib(Tileset.obj) : error LNK2001: �޷��������ⲿ���� __std_find_trivial_8
[2024.09.14-07.39.39:991][763]UATHelper: 打包 (Windows): draco.lib(point_cloud.obj) : error LNK2019: �޷��������ⲿ���� __std_find_trivial_4������ "int * __cdecl __std_find_trivial<int,int>(int *,int *,int)" (??$__std_find_trivial@HH@@YAPEAHPEAH0H@Z) �������˸÷���
[2024.09.14-07.39.39:991][763]UATHelper: 打包 (Windows): s2geometry.lib(s2cell_id.obj) : error LNK2019: �޷��������ⲿ���� __std_init_once_link_alternate_names_and_abort������ "public: __cdecl std::_Init_once_completer::~_Init_once_completer(void)" (??1_Init_once_completer@std@@QEAA@XZ) �������˸÷���
[2024.09.14-07.39.39:991][763]UATHelper: 打包 (Windows): G:\Workproject\1_Yuanshan\yuanshan-model\Binaries\Win64\YuanShan.exe : fatal error LNK1120: 3 ���޷��������ⲿ����
[2024.09.14-07.39.39:991][763]UATHelper: 打包 (Windows): [2/2] WriteMetadata YuanShan.target cancelled
[2024.09.14-07.39.40:033][765]UATHelper: 打包 (Windows): Took 8.0741238s to run dotnet.exe, ExitCode=6

I went to the forum and found that there were relatively few related issues. I tried deleting cesium from the Marketplace, downloaded the latest cesium v2.8.0 from your official website, and put it in the Marketplace, but it still failed. The error message was unable to open LINK: fatal error LNK1181: \ windows-x64 \ asynchronous++. Later, I tried to convert the blueprint into a C++project and put the plugin from the Marketplace into the project file, but the compilation did not pass. It was all external symbols of cesium that could not be parsed. I will put his code below,I don't know what happened, and I hope you can give me some help. I would be very grateful
![1](https://github.com/user-attachments/assets/12f269bf-f86a-43a0-84c7-70e834d1e9d0)
![2](https://github.com/user-attachments/assets/248dd127-68d0-4f22-96af-afabc5841652)

**Comment by kring** [comment] 2024-09-18 00:49
@ClaspU those kinds of errors are usually caused by attempting to compile using a version of the MSVC compiler that is too old. UE 5.2 requires MSVC 14.34.31933 or later.

If you're compiling Cesium for Unreal yourself from source, it's also possible that you've inadvertently built cesium-native in the extern directory with a newer version of MSVC, and then are packaging your game using an old one. This happens really easily because the CMake build in the extern directory will use your latest installed MSVC by default, while Unreal Engine is pickier and will use 14.34 if you have that particular version installed. If this is your situation, you can force cesium-native to build with 14.34 by adding `-T version=14.34` to your CMake configure command line.

I'm closing this because I don't think there's any action on our side. If you're still having trouble, please start a thread on the [community forum](https://community.cesium.com/c/cesium-for-unreal/10).

**Closed** 2024-09-18 00:49 UTC
