### ISSUE TITLE
Report 502 when linking TMS, program crashes

### ISSUE THREAD

**Issue by kak0na** [CesiumGS/cesium-unreal#996] opened 2022-11-18 03:34 UTC
UE4.27
uplugins-1.18.0

At runtime, when the CesiumTileMapServiceRasterOverlay in 3dtileActor reports 502 errors, the program will get stuck and then crash

**Comment by kring** [comment] 2023-07-17 03:26
We see frequent (crash) problems with TMS when the nDisplay plugin is enabled, so perhaps that is what's happening here, too. The problem is a conflict with tinyxml2, as both nDisplay and Cesium have their own embedded copy of that library, and they get smooshed into one namespace in a shipping build so that one of the plugin's ends up stuck with the other's version of tinyxml2.

So I'm closing this as a duplicate of #804.

**Closed** 2023-07-17 03:27 UTC
