### ISSUE TITLE
Stretched imagery when loading from local server

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unreal#561] opened 2021-07-22 22:21 UTC
There is a collection of posts on the Community Forums indicating an error when loading datasets from other servers. 
1. https://community.cesium.com/t/cesium-native-terrain-error/14369
2. https://community.cesium.com/t/terrain-from-a-server/14497
3. https://community.cesium.com/t/load-tilemapservice/14506

It could be an imagery issue, but it appears to work fine in CesiumJS typically, so it's likely a bug. 

Here's an image of the issue from the first link - 
![image](https://user-images.githubusercontent.com/39537389/126716632-1787360c-8691-4bf1-ad87-1611761d5dc3.png)

The user in the second link included the following log:
```
LogCesium: Warning: Too many raster overlays

LogPhysicsCore: Error: PHYSX: (/Volumes/Work/Perforce/UE4/Engine/Source/ThirdParty/PhysX3/PhysX_3.4/Source/PhysXCooking/src/mesh/TriangleMeshBuilder.cpp 802) eINVALID_PARAMETER : TriangleMesh::loadFromDesc: desc.isValid() failed!
```

**Comment by kring** [comment] 2021-07-23 01:57
This is caused by the combination of a few things:
1. The terrain isn't coming from Cesium ion, and so it doesn't conform to the latest incarnation of quantized-mesh. Cesium ion communicates which terrain tiles are available (exist) using a "metadata" extension attached to individual tiles. Some other terrain tilers, however, use an older mechanism that is not supported by Cesium for Unreal, where they put the complete inventory of tile availability in the "layer.json" file. As a result, Cesium for Unreal thinks that only the level zero terrain tiles exist and will not use any of the more detailed ones. That's why the globe in the screenshot above looks so blocky. I thought we had an issue for this, but I can't find it, so I wrote CesiumGS/cesium-native#292 to cover this.
2. The imagery smearing is caused by CesiumGS/cesium-native#93. This is a minor problem when full-detail terrain tiles are available, as we see with Cesium World Terrain. But because of problem 1 above, we're only getting the root tiles, and that makes the imagery projection discontinuity extremely obvious. More detail about that side of it can be found here: https://github.com/CesiumGS/cesium-native/issues/274

I don't think it has anything to do with a local server, it's only the format of the terrain (regardless of source) that matters.

**Comment by argallegos** [comment] 2021-07-27 19:26
Thanks for these resources, @kring! To clarify, is there currently a fix to this issue that I can point users to? It looked like the solution in https://github.com/CesiumGS/cesium-native/issues/274 may not cover it, unless I missed something.

**Comment by kring** [comment] 2021-07-28 01:41
No, there's currently no fix or workaround on the Cesium for Unreal side. I don't know if the tools that generated these datasets have been or could be updated to solve the problem from that side.

**Comment by kring** [comment] 2021-07-28 01:42
I mean, there's one clear workaround worth considering: use Cesium ion. :)

**Comment by Buceawangcheng** [comment] 2021-07-29 01:26
At present, is there a problem with the terrain that will cause the dislocation of the image? But my terrain is correct and can be loaded normally .
I also have this problem. It seems that there is a problem with the triangulation of the terrain. Is this a problem caused by the mismatch between the image resolution and the terrain resolution? 
![terrain](https://user-images.githubusercontent.com/41284742/127416493-a274bcb2-73ba-42a4-bcea-d6e5cd09986f.png)
Fortunately, the image of the area I focused on was displayed correctly. 
![correct](https://user-images.githubusercontent.com/41284742/127416720-b61f2109-ef07-46af-8a3d-854f964e8de3.png)
Only when the camera rises to the global range, the image is wrong (level 0-4?). Local area is correct (maybe wrong, but I can’t see it).
Thanks to the cesium for unreal team .

**Comment by kring** [comment] 2021-07-29 01:33
Any tile that crosses approximately +/- 85 degrees latitude is potentially going to have imagery problems. And also geometry problems when upsampled (e.g. when the imagery is higher resolution than the terrain). At levels 0-4 the tiles are pretty big and will extend well below that 85 degrees.

**Comment by kring** [comment] 2021-08-05 01:34
This is caused by a combination of CesiumGS/cesium-native#292 and CesiumGS/cesium-native#93. Closing as a duplicate.

**Closed by kring** 2021-08-05 01:34 UTC
Labels: bug
