### ISSUE TITLE
about vector tile

### ISSUE THREAD

**Issue by newpeople123** [CesiumGS/cesium-unreal#1361] opened 2024-02-23 01:15 UTC
The latest version already supports raster tiles (WMTS). Are there any plans to support loading vector tiles (such as GeoJSON, TopoJSON, Mapbox vector tile)?

**Comment by j9liu** [comment] 2024-02-23 15:51
Hi @newpeople123,

We have an issue for vector tiles [here](https://github.com/CesiumGS/cesium-unreal/issues/628), but currently we don't have a timeline for when we will be able to address it. You're welcome to chime in on that issue with your specific requests / needs, or just to +1!

Closing this as a duplicate of the issue.

**Closed by j9liu** 2024-02-23 15:51 UTC
