### ISSUE TITLE
Incorrect tile culling behavior with Cartographic Polygon

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-unreal#808] opened 2022-03-31 20:34 UTC
First reported here - https://community.cesium.com/t/intersected-tilesets-incorrect-behavior-with-cartographic-polygon/17865

There appears to be an issue with tile culling and Cartographic Polygons on certain tilesets. ~~This issue only appears in 4.26, it behaves as expected in 4.27~~. Tiles along the boundary of the cartographic polygon will be culled prematurely and inconsistently.

- The tile is fully culled, and does not appear in wireframe view
- Disabling `Exclude Tiles Inside` on the Polygon Raster Overlay does not fix the issue
- The issue does not occur unless a cartographic polygon is being used on the tileset
- If you delete the polygon overlay from the tileset while the issue is occurring, the tiles along the border that were in view at the time you deleted the overlay will continue to demonstrate the behavior until you manually refresh the tileset. As far as I can tell, tiles that were out of view at the time behave regularly.
- All the tilesets that have shown this behavior are using spheres as their bounding volumes.

**Comment by argallegos** [comment] 2022-04-01 19:37
Apparently it's not just 4.26 - the user who reported it is using 4.27. For some additional information, it looks like all the tilesets that are exhibiting this are using sphere bounding volumes. Could that be causing the issue?

Another note that may or may not be related - the user who reported this is using PhysX, and not Chaos.

**Comment by nithinp7** [comment] 2022-04-01 20:35
@argallegos Can you try rendering the rasterized polygon texture to some color like red instead of using it as an opacity mask? Also double check if Exclude Tiles Inside is unchecked, if unchecking that option does not make the hole go away, this is a texture problem (so visualizing the texture with a color may make it more apparent).

**Comment by argallegos** [comment] 2022-04-01 21:02
@nithinp7 Testing with red instead of an opacity mask behaves exactly as you would expect, except tiles will still go missing around the perimeter of the polygon. Unchecking Exclude tiles inside does not make the hole go away, unfortunately. The one thing I'm noticing is that it's specifically the tiles that are halfway inside and halfway outside the polygon that go missing.

**Comment by argallegos** [comment] 2022-04-04 19:12
For some reason or another, upgrading Cesium for Unreal from 1.11.0 to 1.12.0 seems to have resolved this. So if you're experiencing this issue, try updating the plugin. 

That being said, there still could be an underlying issue that may pop up again.

@nithinp7 and I did some testing. It also occurs on the Aerometrex Denver tileset (which uses sphere bounding volumes?). Some more notes:

- Happens only when a cartographic polygon is applied to a tileset, regardless of whether or not the overlay is tied to a material layer. Eg: putting in a nonexistent material layer key still causes the issue.
- Only culls polygons on the perimeter of the cartographic polygon
- Disabling Frustrum Culling and Fog Culling does not change the issue
- Tiles only go missing when near the camera
- The tiles don't seem to be counted as "culled" when Log Selection Stats is enabled.

Pictures (On the Aerometrex Denver tileset):
The red tint indicates the area inside the polygon. Exclude Tiles Inside is disabled. 
![image](https://user-images.githubusercontent.com/39537389/161615067-8ece62ee-7409-4e82-81d6-837eff495715.png)
![image](https://user-images.githubusercontent.com/39537389/161615121-330f2ca6-cb8a-4fc5-ad86-c86d2340a65a.png)

**Comment by kring** [comment] 2022-04-05 06:14
My guess: upsampling is generating an invalid mesh. Upsampling is driven by texture coordinates, and also by the expected range of projected coordinates in the tile as indicated by the bounding volume. If these go wrong, it ends up looking a bit like that.

**Comment by kring** [comment] 2022-05-09 12:48
@joseph-kaile this is probably another symptom of the incorrect upsampling that you're hunting down.

**Comment by nithinp7** [comment] 2022-05-09 14:43
@kring @joseph-kaile Just reiterating that the issue actually _went away_ on its own after the 1.11 to 1.12 update. But we never narrowed down why. I suspect Joseph may have fixed this implicitly while working on something else at that time. We only left the issue open in the absence of a concrete theory as to why it stopped happening. Also iirc it only happened for sphere bounding volumes.

**Comment by kring** [comment] 2022-05-09 23:23
ok thanks @nithinp7, I had missed that. It certainly looks like the same thing to me, but it could be a similar symptom caused by a different problem. If we're not currently seeing a problem, there's probably not much value here for Joseph's investigations, so I'll close this.

**Closed by kring** 2022-05-09 23:23 UTC
Labels: bug
