### ISSUE TITLE
Cesium3DTileset Navigation Mesh is not generated for Actor (cannot be visualized?)

### ISSUE THREAD

**Issue by sekiguchi-yohei** [CesiumGS/cesium-unreal#704] opened 2021-12-08 09:39 UTC
I want to apply Unreal Engine's Navigation System to a 3DTiles building model loaded in cesium for unreal, but Navigation Mesh does not appear on the 3D model.
https://docs.unrealengine.com/4.27/en-US/InteractiveExperiences/ArtificialIntelligence/NavigationSystem/BasicNavigation/

 * Process
1.  In the Cesium3DTileset Actor details, select [Cesium]-[Source], select [From Url], and enter the path to tileset.json.
2. The 3D model is displayed in the viewport.
（So far, so good.）

3. Place NavMeshBoundsVolume on the loaded 3D model.
※[Project settings]-[Runtime Generation]: Static
4. visualize the final Navigation Mesh by pressing the P key.
  → Navigation Meshes are not visualized.

* Environmental Information
OS Version：Windows Server2019
RAM：16GB
Unreal Engine Version：4.26.2
cesium for unreal Version：v1.5.1

If there is a way to solve this problem, please let me know.
Also, if you are saying that fixing a specific part of the cesium for unreal code will solve the issue, can you please tell me about it?

**Comment by argallegos** [comment] 2022-07-06 21:37
Duplicate of https://github.com/CesiumGS/cesium-unreal/issues/327, closing. See linked issue for further discussion.

**Closed by argallegos** 2022-07-06 21:37 UTC
Labels: enhancement
