### ISSUE TITLE
The same method, build UE4Cesium plugin successfully, UE5Cesium plugin fail?

### ISSUE THREAD

**Issue by JoinKomorebi** [CesiumGS/cesium-unreal#901] opened 2022-07-11 10:09 UTC
Before, I was able to successfully compile the Cesium plugin to UE4. I used the same method to compile the UE5 plugin, but the compilation faile.I run the solution and run the project and it shows something like。I hope to get your help。Thanks。
![Snipaste_2022-07-11_17-35-27](https://user-images.githubusercontent.com/104044166/178241037-c23ba8cc-058c-4a79-b917-e3b36d24678f.png)
![Snipaste_2022-07-11_17-58-22](https://user-images.githubusercontent.com/104044166/178241047-089f0b13-1c40-4333-890a-26c8834e7a7b.png)
![Snipaste_2022-07-11_17-58-30](https://user-images.githubusercontent.com/104044166/178241054-1669bbcd-0636-47b7-b8e7-d5ea3625fe3a.png)
d

**Comment by kring** [comment] 2022-07-13 04:18
As I understand it, this linker error is caused by a backward compatibility bug in (some versions?) of VS2022. There are more details here:
https://developercommunity.visualstudio.com/t/-imp-std-init-once-complete-unresolved-external-sy/1684365#T-N10047968

And previous discussion of the issue on the community forum:
https://community.cesium.com/t/packaging-error-s2geometry-lib/18869/2

Closing this as there is no action for Cesium for Unreal itself.

**Closed by kring** 2022-07-13 04:18 UTC
