### ISSUE TITLE
UE 5.1: Crash on level switch with world partition

### ISSUE THREAD

**Issue by nithinp7** [CesiumGS/cesium-unreal#1008] opened 2022-12-05 20:59 UTC
We don't currently use world partition and in fact world partition probably does not work with georeference origin changes, but it shouldn't crash. Steps to reproduce afaict:
- Open the template "Open World" level.
- Add Cesium World Terrain (I imagine any tileset works).
- Save the level and switch to another level, even double clicking on the same level in the asset browser should cause the issue to happen.
- If the crash doesn't happen yet, switch back to the level and try switching away again.

I'm not sure if this is particular to 5.1 or if this existed in 5.0 as well. The crash stack trace seems to indicate that the world partition system is trying to unload some actor (I assume the tileset) and failing some cast along the way. The world partition system should not have to interact with tilesets, since tilesets should be loaded all the time, but maybe there's something else we need to specify on the tileset actors to let Unreal know that.

**Comment by kring** [comment] 2022-12-05 22:29
This looks like it might be a duplicate of #941.

**Closed** 2022-12-05 22:52 UTC
