### ISSUE TITLE
load massive photogrammetry model stutter

### ISSUE THREAD

**Issue by WxpGiser** [CesiumGS/cesium-unreal#701] opened 2021-12-06 09:08 UTC
PC ：i9-10900K  RTX-3070  RAM 64G

when loading massive photogrammetry model a while，video memory has being feed to the full，sometimes releasing video memory with a little stutter，also has a crash as follow：

<img width="563" alt="16385238253397" src="https://user-images.githubusercontent.com/20197113/144818289-6e264f9b-d233-4390-a4fb-89f047644db1.png">

**Comment by wxp1989** [comment] 2021-12-07 03:39
I find a solution，it's work

<img width="614" alt="16388482962564" src="https://user-images.githubusercontent.com/20197113/144961945-6898d71f-b203-4da6-950a-75ef8e93c4e2.png">

**Comment by kring** [comment] 2021-12-07 04:09
Are you using the latest version of Cesium for Unreal, v1.8.1? If the pauses are caused by UE's garbage collection, you should see much better behavior in the latest release.

**Comment by wxp1989** [comment] 2021-12-07 07:34
v1.8.1 get much better experience with less video memory usage, you have done a great work.

when I set MaximumCachedBytes to 8GB, there is still have stutter ,maybe should use compressed texture when data is too large.

**Comment by kring** [comment] 2021-12-07 09:44
Yep, we'll have KTX2 support before too long. See #691. It's possible that the remaining stutter at 8GB is caused by exceeding your available system memory and needing to swap to disk. Even though you said your system has 64GB, the way the 8GB is measured means it can actually require a lot more than that, especially if you're using multiple tilesets.

**Comment by WxpGiser** [comment] 2021-12-07 09:54
Can the remaining stutter is because of the video memory is not enough? Releasing video memory with stutter commonly。

**Comment by kring** [comment] 2021-12-07 11:03
It's possible. Setting MaximumCachedBytes to 8GB will hit both system and video memory _very_ hard.

**Comment by WxpGiser** [comment] 2021-12-08 01:19
It's happened. By the way, video memory is not just taken by this tileset.

**Comment by kring** [comment] 2022-05-09 08:52
Closing this because I don't think there's any further action here.

**Closed by kring** 2022-05-09 08:52 UTC
