### ISSUE TITLE
Patches in imagery

### ISSUE THREAD

**Issue by ankitpentashield** [CesiumGS/cesium-unreal#1525] opened 2024-09-27 04:53 UTC
![image](https://github.com/user-attachments/assets/b48e832e-e7f9-40f4-8c9d-c692f597e6e3)

I have tried to put up most basic level with cesium3dtileset actor with two raster overlay component and cesiumsunsky. I have tried to adjust solar time and time zone suitable. When I play it is showing the patches in the globe imagery. Can anyone from community please guide me with this issue?

I have tried to adjust maximum screen space error default 16 to 2. In that can it is not showing patches. But its is taking too much time to load.

**Comment by j9liu** [comment] 2024-09-27 19:49
Hi @ankitpentashield,

Could you share more information with us, including:

- What version of Unreal Engine are you using?
- What dataset is this -- Cesium World Terrain? Google Photorealistic 3D Tiles? Do you see this happen on both tilesets, or only one?
- Could you try using the Dynamic Pawn instead? We don't offer a **Globe Pawn** option in the menu, perhaps you're using a modified version of the plugin?

**Comment by ankitpentashield** [comment] 2024-09-28 12:37
I am using Unreal 5.3.2 with latest cesium plugin build from screen-space-controller branch I have tried using the dynamic pawn but issue still persist. Regarding the data I am using preprocessed and tiled data downloaded from cesium ion for offline serving and I am using earth emagery from luciad

**Comment by Apollo199999999** [comment] 2024-10-01 11:16
I am encountering a similar issue. When I zoom out, the terrain appears to be "patchy". I am using the Google Photorealistic 3D tiles in Unreal 5.4.
![image](https://github.com/user-attachments/assets/2b1d168f-7b36-465f-b6a0-cc369dcdf3cc)

**Comment by kring** [comment] 2024-10-02 04:38
@ankitpentashield can you please check if you're able to reproduce this problem in an official release of the plugin? It's hard to say what bugs might be lurking in a work-in-progress branch like `screen-space-controller`.

**Comment by kring** [comment] 2024-10-02 04:39
@Apollo199999999 I can't say for sure, but your screenshot looks like you possible have multiple tilesets displaying on top of each other, for example both Cesium World Terrain and Google Photorealistic 3D Tiles. Is that a possibility?

**Comment by kring** [comment] 2024-10-02 11:18
Please see #1530 for an explanation and fix for this issue.

**Comment by Apollo199999999** [comment] 2024-10-02 11:47
I see, thanks for the quick response.

**Closed** 2024-10-25 15:15 UTC
