### ISSUE TITLE
Crash when switching between sublevels

### ISSUE THREAD

**Issue by gvindiol** [CesiumGS/cesium-unreal#673] opened 2021-10-29 04:56 UTC
We recently upgraded from CesiumForUnreal 1.6.0 -> 1.6.3
We have several sublevels within the same general area and also a larger 3D Tile that overlaps all of them in our persistent level.

![image](https://user-images.githubusercontent.com/44582391/139378173-418a11ca-10b8-420b-ae23-580d9e4fd187.png)

**Comment by gvindiol** [comment] 2021-10-29 19:47
I was able to compile now but there's a new issue with the sublevels.

- If I go in/out the CesiumGeoference sphere from sublevel A to Sublevel B. Sublevel A will not unload but migrate to the CesiumGeoreference for sublevel B and now the contents of Sublevel A and B are overlapping. The processes will repeat if I go to sublevel B to sublevel C. None of the sublevels unload and stack on-top the next CesiumGeoreference location. 

Maybe a related thing to point out is that we also have buttons to inaccurateFlytoLocationLongLatHeight() the dynamic pawn to earth view and ground view. We take the current DynamicPawn location and TransformUEtoLongLatHeight() to transition the DyanmicPawn Camera. I made some adjustments for the introduction of GlobeAnchor.

![image](https://user-images.githubusercontent.com/44582391/139493311-e97234b5-2c90-494f-8f2f-e9e76b96bce3.png)

If I go from ground view to earth view using this button then the camera orientation is oriented differently (moving mouse up will turn right, etc)

**Comment by kring** [comment] 2021-10-29 21:47
Ok, thanks, that is quite surprising but I'll check it out. That behavior with the sublevels not unloading: is that in editor, play-in-editor, packaged game? On the georeference details panel, do your sub levels show up as enabled?

**Comment by gvindiol** [comment] 2021-10-29 22:23
Packaged Shipping Release for Windows.
Yes, I see in the CesiumGeoreference > Details panel that all related sublevels have an Enabled checkmark on.

**Comment by kring** [comment] 2021-10-30 11:51
@gvindiol I've tried to reproduce the issue with sublevels not unloading, but I haven't been able to. Using UE 4.27 and the version of the plugin linked above, I did the following:

1. Created a new empty level in a subdirectory.
2. Added Cesium World Terrain + Bing Maps Aerial imagery, Cesium SunSky, and Dynamic Pawn to the new level.
3. Enabled World Composition.
4. From the Levels panel, created a new Layer called Cesium.
5. Created a new sub-level and assigned it to the Cesium layer. Double-clicked the level to make it active.
6. Add a cube to the sub-level and scaled it to 100.0 to make it easier to find.
7. Created a second new sub-level and assigned it to the Cesium layer. Double-clicked the level to make it active.
8. Moved the editor camera a short distance away and pressed the Place Georeference Origin Here button on the Cesium Georeference panel.
9. Added a cone to this second level, again with a scale of 100.0.
10. Pressed Play, and observed that as I move closer to the center of the first sub-level, the cube appears, and when I move closer to the second sub-level, the cube disappears and the cone reappears. I can move back and forth to switch between them.

I also did a shipping build and observed that it works there too.

Can you spot a difference from what you're doing? Are you able to share a project with me that exhibits the problem, so that I can take a look?

**Comment by gvindiol** [comment] 2021-10-30 20:12
I'm only familiar with the original tutorial for sublevels https://cesium.com/learn/unreal/unreal-sublevels/

I noticed that with this version of cesium there is no sub-level index. So I'm not sure how to change the LatLongHeight of the current sublevel origin that actors would be offset from. So when I load a sublevel in, how do I change the scenes origin?

Sure, can I email you the link?

**Comment by kring** [comment] 2021-10-30 23:29
In the new version, you switch between sub-levels just by double-clicking them on the Levels panel. No need to use the sub-level index on the CesiumGeoreference anymore. To set the lat/lon/height of the sub-level, you can double-click it in the Levels panel to activate it, then edit the Origin Latitude/Longitude/Height properties on the CesiumGeoreference. You can also edit the properties in the sub-level section of Cesium Georeference, but that won't immediately update your view to match so it can be confusing.

Yes please email me the link. Use my first name at cesium.com. Or the email address in my github profile is fine too.

**Comment by kring** [comment] 2021-11-01 10:37
Quick update on this. I have @gvindiol's project, but I'm so far not able to reproduce the problem with the contents of a level "sticking" after the camera leaves the Load Radius. But I can reproduce the problem where the camera goes haywire after an `InaccurateFlytoLocationLongLatHeight`. It's caused by the -90 degree pitch value. Some kind of gimbal lock maybe? Changing the target pitch to -89.9 degrees works around the problem. I'll write a separate issue for it.

**Comment by gvindiol** [comment] 2021-11-29 10:26
We were able to correct the sticky level problem by unchecking "Origin Rebase Inside" within the CesiumGeoreference Actor with no noticeable differences yet.

> I was able to compile now but there's a new issue with the sublevels.
> 
> * If I go in/out the CesiumGeoference sphere from sublevel A to Sublevel B. Sublevel A will not unload but migrate to the CesiumGeoreference for sublevel B and now the contents of Sublevel A and B are overlapping. The processes will repeat if I go to sublevel B to sublevel C. None of the sublevels unload and stack on-top the next CesiumGeoreference location.

**Closed** 2022-03-13 10:12 UTC
