### ISSUE TITLE
high-resolution images overlay low-resolution terrain

### ISSUE THREAD

**Issue by flyskyosg** [CesiumGS/cesium-unreal#1068] opened 2023-03-30 03:57 UTC
I have a 10-level tin-terrain layer and a 20-level image layer. 

The previous method found that the high-definition image cannot be loaded. 

Has the latest version solved this problem?

Thank you.

**Comment by kring** [comment] 2023-03-30 03:58
This is a common scenario, and should be supported. In fact, I'm not aware of it ever having been broken. In which version did you see a problem?

**Comment by flyskyosg** [comment] 2023-04-04 00:25
In the v1.0 version, the tin terrain cannot be subdivided. When the terrain level is relatively low, images of the same level can be loaded, but images of higher levels cannot be loaded.

**Comment by kring** [comment] 2023-04-04 00:38
Ok, I don't remember that being the case, but it's possible. That was over two years ago now, and honestly that's probably the least of your problems if you're still using v1.0! :) Have you confirmed that it's working in the newer versions?

**Comment by kring** [comment] 2023-07-17 02:57
Closing becase it's seemingly only a problem in a very old version, and because of no update since April.

**Closed by kring** 2023-07-17 02:57 UTC
